name: Run End-to-End Test Suite

on:
  pull_request:
    branches: [main, develop]
    
permissions:
  id-token: write
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  ubuntu-run:
    runs-on: ['self-hosted', 'linux', 'x64']
    strategy:
      fail-fast: false
      matrix:
        browsers: ['chrome']
    steps:
      - name: Check out🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: NPM install
        uses: ./.github/actions/install-run
        with:
          SHELL_TYPE: 'bash'

      - name: Running cypress check
        uses: ./.github/actions/cypress-run
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SHELL_TYPE: 'bash'
          OS_RUN: 'Ubuntu'
          BROWSER_RUN: ${{ matrix.browsers }}
          RUN_ALL: false
          ENV_CONTENT: ${{ secrets.DEV_ENV }}

      - name: Running Danger check (Ubuntu only)
        uses: ./.github/actions/danger-run
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
